# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-container
  namespace: {{ .Values.rootNamespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-container
  template:
    metadata:
      labels:
        app: frontend-container
    spec:
      containers:
        - name: frontend-container
          image: {{ .Values.frontend.imageURL }}
          ports:
            - containerPort: 3000
          env:
            - name: MY_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MY_SECRET_TOKEN
          volumeMounts:
            - name: env-production-cm
              mountPath: /app/.env.production
              readOnly: true
              subPath: .env.production
      volumes:
        - name: env-production-cm
          configMap:
            name: env-production-cm
            items:
              - key: .env
                path: .env.production
